# Generated by Django 5.2.3 on 2025-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parbrise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uri', models.URLField()),
                ('violated_directive', models.CharField(max_length=255)),
                ('blocked_uri', models.TextField()),
                ('original_policy', models.TextField()),
                ('source_file', models.TextField(blank=True, null=True)),
                ('script_sample', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
