# Generated by Django 5.2.3 on 2025-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parbrise', '0002_cspreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parebrise',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
