# Generated by Django 5.2.3 on 2025-07-23 23:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parbrise', '0003_alter_parebrise_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Journal d'activité", 'verbose_name_plural': "Journaux d'activité"},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de la notification (si applicable)", null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('REGISTER', 'Inscription'), ('ROLE_CHANGE', 'Changement de rôle'), ('USER_CREATE', 'Création utilisateur'), ('USER_UPDATE', 'Mise à jour utilisateur'), ('USER_DELETE', 'Suppression utilisateur'), ('VERIFICATION', 'Vérification logo'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('PROFILE_UPDATE', 'Mise à jour profil'), ('SYSTEM', 'Notification système')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='parbrise_ac_action_4b46f1_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity'], name='parbrise_ac_severit_f01e03_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='parbrise_ac_timesta_fb7db0_idx'),
        ),
    ]
