# Generated by Django 5.2.3 on 2025-07-23 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parbrise', '0004_alter_activitylog_options_activitylog_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Entrée du journal', 'verbose_name_plural': 'Journal des activités'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration automatique", null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['expires_at'], name='parbrise_ac_expires_ba19ed_idx'),
        ),
    ]
