# Generated by Django 5.2.3 on 2025-07-23 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parbrise', '0005_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='parbrise_ac_action_4b46f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='parbrise_ac_severit_f01e03_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='parbrise_ac_timesta_fb7db0_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='parbrise_ac_expires_ba19ed_idx',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='severity',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('REGISTER', 'Inscription'), ('ROLE_CHANGE', 'Changement de rôle'), ('USER_CREATE', 'Création utilisateur'), ('USER_UPDATE', 'Mise à jour utilisateur'), ('USER_DELETE', 'Suppression utilisateur'), ('VERIFICATION', 'Vérification logo'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('PROFILE_UPDATE', 'Mise à jour profil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
