# Generated by Django 5.2.3 on 2025-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parbrise', '0006_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrier',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('ouvrier', 'Ouvrier')], default='ouvrier', max_length=20),
        ),
    ]
